services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: BOT_TOKEN
        sync: false     # Value set in the Render dashboard, not in repo
