services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: "7597041420:AAG08GC3pzwKT0S2kG0bl3xX0NCSbdLNG6A"  # Replace with your bot's token
